### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lele012** [wondonghyeon/protest-detection-violence-estimation#7]
Hi，how to download the image dataset ?

**Comment by 1057520143** [comment]
I found the email link of the author: won.donghyeon@gmail.com, and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

**Comment by chi0612** [comment]
> Hi，how to download the image dataset ?

Did you get the author's reply?

**Comment by wangran1999** [comment]
> 



> 
Hi bro, do you have the dataset? I really in need of this dataset, and I have written an email to the author, but he hasn't replied to me till now. Could you please send me the dataset? Thank you very much!

**Comment by wondonghyeon** [comment]
> Hi bro, do you have the dataset? I really in need of this dataset, and I have written an email to the author, but he hasn't replied to me till now. Could you please send me the dataset? Thank you very much!

@wangran1999 , do you mind sending me another email? Thanks.

**Comment by wangran1999** [comment]
Dear Professor,
&nbsp; &nbsp; &nbsp;thank you very much for your reply, and Now I have written another email to ***@***.***), I am really looking forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wondonghyeon/protest-detection-violence-estimation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wondonghyeon/protest-detection-violence-estimation] dataset (#7)





  
Hi bro, do you have the dataset? I really in need of this dataset, and I have written an email to the author, but he hasn't replied to me till now. Could you please send me the dataset? Thank you very much!
  
@wangran1999 , do you mind sending me another email? Thanks.

**Comment by wangran1999** [comment]
Dear Professor, I have witten an email to you again. Could you tell me whether you have received it? I'm sorry to bother you, but I'm really in need of the dataset recently. Thank you a lot.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wondonghyeon/protest-detection-violence-estimation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wondonghyeon/protest-detection-violence-estimation] dataset (#7)





  
Hi bro, do you have the dataset? I really in need of this dataset, and I have written an email to the author, but he hasn't replied to me till now. Could you please send me the dataset? Thank you very much!
  
@wangran1999 , do you mind sending me another email? Thanks.

**Comment by tylgczq** [comment]
> I found the email link of the author: [won.donghyeon@gmail.com](mailto:won.donghyeon@gmail.com), and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

I am a bit in urgent need of this dataset, and I have also sent an email to the author, but the author has not replied yet. Would you mind sending me a copy. sxstysczq@163.com   thank u

**Comment by tylgczq** [comment]
> Dear Professor, I have witten an email to you again. Could you tell me whether you have received it? I'm sorry to bother you, but I'm really in need of the dataset recently. Thank you a lot.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wondonghyeon/protest-detection-violence-estimation" ***@***.***&gt;; 发送时间:&nbsp;2023年3月27日(星期一) 晚上6:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wondonghyeon/protest-detection-violence-estimation] dataset (#7) Hi bro, do you have the dataset? I really in need of this dataset, and I have written an email to the author, but he hasn't replied to me till now. Could you please send me the dataset? Thank you very much! @wangran1999 , do you mind sending me another email? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

have you got the datasets？ would you mind send me a one？sxstysczq@163.com

**Comment by wondonghyeon** [comment]
Please refer to this thread
https://github.com/wondonghyeon/protest-detection-violence-estimation/issues/10#issuecomment-2011074183
