### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by MrWangg1992** [wondonghyeon/protest-detection-violence-estimation#8]
Hi，how can i  download the image dataset? I mean i couldn't find your email on the README page

**Comment by 1057520143** [comment]
I found the email link of the author: won.donghyeon@gmail.com, and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

**Comment by chi0612** [comment]
> Hi，how can i download the image dataset? I mean i couldn't find your email on the README page

Did you get the author's reply?

**Comment by JolinFeng** [comment]
> 

Hello, could you please send me a copy of the dataset? Thank you very much, here is my email zoeyfeng666@gmail.com

**Comment by tylgczq** [comment]
> I found the email link of the author: [won.donghyeon@gmail.com](mailto:won.donghyeon@gmail.com), and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

Can you share a copy with me? I also sent an email to the author, but I haven't received a response for a long time。sxstysczq@163.com    thank u

**Comment by saifuddinsabbir** [comment]
Hello. Could you please share a copy of the dataset with me? I need it now badly.  This is my email: [saifuddin.sabbir@gmail.com](url). Thank you.

**Comment by yangh-zzf-itcast** [comment]
> I found the email link of the author: [won.donghyeon@gmail.com](mailto:won.donghyeon@gmail.com), and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

Hi. Could you please share a copy of the dataset with me? I need it now badly. This is my email: 2459846416@qq.com. Thank you.

**Comment by DingLe139** [comment]
> I found the email link of the author: [won.donghyeon@gmail.com](mailto:won.donghyeon@gmail.com), and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck

Hi,could u share a copy with me? i really need the dataset.This is my email:dingle139@163.com

**Comment by DingLe139** [comment]
> > I found the email link of the author: [won.donghyeon@gmail.com](mailto:won.donghyeon@gmail.com), and sent the email address of the requested data set to the author. The author has replied to me. You can also try sending an email to the author. Good luck
> 
> Hi. Could you please share a copy of the dataset with me? I need it now badly. This is my email: [2459846416@qq.com](mailto:2459846416@qq.com). Thank you.

halo，请问您有收到数据集吗？可否麻烦您分享一下呢，我现在也十分需要相关的数据集，非常感谢，我的邮箱：dingle139@163.com，再次感谢！

**Comment by wondonghyeon** [comment]
Please refer to this thread
https://github.com/wondonghyeon/protest-detection-violence-estimation/issues/10#issuecomment-2011074183
